"""add name to user

Revision ID: 4486e87eddb4
Revises: ce4e8e42efc8
Create Date: 2026-03-15 16:26:34.147028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4486e87eddb4'
down_revision: Union[str, Sequence[str], None] = 'ce4e8e42efc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('app_user', sa.Column('name', sa.String(length=255), nullable=True))
    op.execute("UPDATE app_user SET name = ''")
    op.alter_column('app_user', 'name', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'name')
    # ### end Alembic commands ###
