"""initial

Revision ID: ce4e8e42efc8
Revises: 
Create Date: 2026-03-15 01:17:26.605107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4e8e42efc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('max_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('tg_id', name='uq_user_tg_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('game_status', sa.Enum('WAITING_FOR_PLAYERS', 'IN_PROGRESS', 'FINISHED', name='gamestatusenum'), nullable=False),
    sa.Column('game_trading_session_round', sa.Integer(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index('ix_game_chat_id', 'game', ['chat_id'], unique=False)
    op.create_index('ix_game_created_at', 'game', ['created_at'], unique=False)
    op.create_table('company_shares',
    sa.Column('company_share_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('company_share_name', sa.String(), nullable=False),
    sa.Column('company_share_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_share_id'),
    sa.UniqueConstraint('game_id', 'company_share_name', name='uq_company_share_game_name')
    )
    op.create_index('ix_company_shares_game_id', 'company_shares', ['game_id'], unique=False)
    op.create_table('game_user',
    sa.Column('game_user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('game_user_id'),
    sa.UniqueConstraint('game_id', 'user_id', name='uq_game_user')
    )
    op.create_index('ix_game_user_game_id', 'game_user', ['game_id'], unique=False)
    op.create_index('ix_game_user_user_id', 'game_user', ['user_id'], unique=False)
    op.create_table('user_balance',
    sa.Column('user_balance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pure_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('company_share_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['game_user_id'], ['game_user.game_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_balance_id'),
    sa.UniqueConstraint('game_user_id')
    )
    op.create_table('user_company_share',
    sa.Column('user_company_share_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_share_id', sa.BigInteger(), nullable=False),
    sa.Column('company_share_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_share_id'], ['company_shares.company_share_id'], ),
    sa.ForeignKeyConstraint(['game_user_id'], ['game_user.game_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_company_share_id'),
    sa.UniqueConstraint('game_user_id', 'company_share_id', name='uq_user_company_share')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company_share')
    op.drop_table('user_balance')
    op.drop_index('ix_game_user_user_id', table_name='game_user')
    op.drop_index('ix_game_user_game_id', table_name='game_user')
    op.drop_table('game_user')
    op.drop_index('ix_company_shares_game_id', table_name='company_shares')
    op.drop_table('company_shares')
    op.drop_index('ix_game_created_at', table_name='game')
    op.drop_index('ix_game_chat_id', table_name='game')
    op.drop_table('game')
    op.drop_table('app_user')
    # ### end Alembic commands ###
